# Generated by Django 5.2.8 on 2025-12-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_facebook_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instagram_link',
            field=models.URLField(blank=True, help_text='Link to your Instagram profile'),
        ),
    ]
