# Generated by Django 5.2.8 on 2025-12-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile_instagram_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Enter number with country code (e.g., +213541120811)', max_length=20),
        ),
    ]
