# Generated by Django 5.2.8 on 2025-12-29 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile_whatsapp_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='whatsapp_number',
            new_name='whatsapp_link',
        ),
    ]
